import Head from "next/head";
import { useState } from "react"; // Import useState
import { SiteHeader } from "~/components/header";

import { api } from "~/utils/api";
import { Item, getRandomItem } from "../utils/crateLogic"; // Import the logic from crateLogic.ts

export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  // Step 1: Create a state variable to hold the received item.
  const [receivedItem, setReceivedItem] = useState<Item | null>(null);

  // Step 2: Function to handle the button click and set the received item.
  function handleOpenCrate() {
    const item = getRandomItem();
    setReceivedItem(item);
  }

  function getColorForRarity(rarity: string) {
    switch (rarity) {
      case "common":
        return "text-gray-500";
      case "uncommon":
        return "text-green-500";
      case "rare":
        return "text-blue-500";
      case "epic":
        return "text-purple-500";
      case "legendary":
        return "text-yellow-500";
      default:
        return "text-gray-500"; // Default to gray for unknown rarities
    }
  }
  

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SiteHeader />
      <main className="flex min-h-screen flex-col items-center justify-center">
        {receivedItem && (
          <div className="mb-2">
            <p>
              You received: {receivedItem.name} (
              <span
                className={`${getColorForRarity(
                  receivedItem.rarity,
                )} font-bold`}
              >
                {receivedItem.rarity}
              </span>{" "}
              rarity)
            </p>
          </div>
        )}

        <button
          onClick={handleOpenCrate}
          className="rounded bg-black px-4 py-2 font-bold text-white hover:bg-gray-800"
        >
          Open AstroCrate
        </button>
      </main>
    </>
  );
}
