import Head from "next/head";
import { useState } from "react"; // Import useState
import { SiteHeader } from "~/components/header";
import { Button } from "@/components/ui/button";

import { api } from "~/utils/api";
import { type Item, getRandomItem } from "../utils/crateLogic"; // Import the logic from crateLogic.ts

export default function Home() {
  // Step 1: Create a state variable to hold the received item.
  const [receivedItem, setReceivedItem] = useState<Item | null>(null);

  // Step 2: Function to handle the button click and set the received item.

  function getColorForRarity(rarity: string) {
    switch (rarity) {
      case "common":
        return "text-gray-500";
      case "uncommon":
        return "text-green-500";
      case "rare":
        return "text-blue-500";
      case "epic":
        return "text-purple-500";
      case "legendary":
        return "text-yellow-500";
      default:
        return "text-gray-500"; // Default to gray for unknown rarities
    }
  }

  const crateHandler = api.example.getCrates.useMutation()


  const generateRandomItemListWithSelectedItem = () => {
    crateHandler.mutate();
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SiteHeader />
      <main className="flex min-h-screen flex-col items-center justify-center">
        {crateHandler.data ? (
          <>
            {crateHandler.data.list.map((item: Item, index) => (
              <div key={index} className="flex items-center justify-center flex-col bg-gray-200 rounded-xl p-3">
                <div className=" font-bold">{item.name}</div>
                <div className={getColorForRarity(item.rarity)}>{item.rarity}</div>
              </div>
            ))}
          </>
        ) : (
          <div className="text-2xl font-bold">Loading...</div>
        )}

        <button
          onClick={generateRandomItemListWithSelectedItem}
          className="rounded bg-black px-4 py-2 font-bold text-white hover-bg-gray-800"
        >
          Open AstroCrate
        </button>
      </main>
    </>
  );
}
