import Head from "next/head";
import { useState } from "react";
import { SiteHeader } from "~/components/header";
import { Button } from "@/components/ui/button";
import { api } from "~/utils/api";
import { type Item, getRandomItem } from "../utils/crateLogic";

export default function Home() {
  const [receivedItem, setReceivedItem] = useState<Item | null>(null);

  function getColorForRarity(rarity: string) {
    switch (rarity) {
      case "common":
        return "text-gray-500";
      case "uncommon":
        return "text-green-500";
      case "rare":
        return "text-blue-500";
      case "epic":
        return "text-purple-500";
      case "legendary":
        return "text-yellow-500";
      default:
        return "text-gray-500";
    }
  }

  const crateHandler = api.example.getCrates.useMutation();

  const generateRandomItemListWithSelectedItem = () => {
    crateHandler.mutate();
  
    const items = document.querySelectorAll(".item-card");
    items.forEach((item, index) => {
      item.classList.add("slot-machine-animation");
  
      if (index === crateHandler.data?.list.length - 1) {
        item.addEventListener("animationend", () => {
          item.classList.remove("slot-machine-animation");
        });
      }
    });
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SiteHeader />
      <main className="flex min-h-screen flex-col items-center justify-center">
        {crateHandler.data ? (
          <>
            {crateHandler.data.list.map((item: Item, index) => (
              <div
                key={index}
                className="item-card flex flex-col items-center justify-center rounded-xl bg-gray-200 p-3"
              >
                <div className=" font-bold">{item.name}</div>
                <div className={getColorForRarity(item.rarity)}>
                  {item.rarity}
                </div>
              </div>
            ))}
          </>
        ) : (
          <div className="text-2xl font-bold">Loading...</div>
        )}

        <button
          onClick={generateRandomItemListWithSelectedItem}
          className="hover-bg-gray-800 rounded bg-black px-4 py-2 font-bold text-white"
        >
          Open AstroCrate
        </button>
      </main>
    </>
  );
}
