// Define a type for an item with a rarity.
export type Item = {
  name: string;
  rarity: "common" | "uncommon" | "rare" | "epic" | "legendary";
};

// Create an array of items with rarities.
const items: Item[] = [
  { name: "Space Food Rations", rarity: "common" },
  { name: "Basic Spacesuit", rarity: "common" },
  { name: "Space Wrench", rarity: "common" },
  { name: "Solar Panel Charger", rarity: "common" },
  { name: "Oxygen Canister", rarity: "common" },
  { name: "Emergency Repair Kit", rarity: "common" },
  { name: "Low-Grade Space Minerals", rarity: "common" },
  { name: "Holographic Star Map", rarity: "common" },
  { name: "Space Radio", rarity: "common" },
  { name: "Gravity Boots", rarity: "common" },
  { name: "Communications Relay", rarity: "common" },
  { name: "Meteorite Sample", rarity: "common" },
  { name: "Space Toolbox", rarity: "common" },
  { name: "Ionized Space Rocks", rarity: "common" },
  { name: "Nebula Souvenir", rarity: "common" },
  { name: "Space Thermos", rarity: "common" },
  { name: "Astronaut's Diary", rarity: "common" },
  { name: "Stellar Calendar", rarity: "common" },
  { name: "Space Dehydrated Snacks", rarity: "common" },
  { name: "Asteroid Ore Sample", rarity: "common" },
  { name: "Space Glue", rarity: "common" },
  { name: "Galactic Compass", rarity: "common" },
  { name: "Quantum Clock", rarity: "common" },
  { name: "Nebula Glowstick", rarity: "common" },
  { name: "Space Blanket", rarity: "common" },
  { name: "Retro Space Arcade Token", rarity: "common" },
  { name: "Space Maintenance Manual", rarity: "common" },
  { name: "Zero-G Beverage", rarity: "common" },
  { name: "Space Recycling Kit", rarity: "common" },
  { name: "Cosmic Pencil", rarity: "common" },
  { name: "Lunar Dust", rarity: "common" },
  { name: "Space Keychain", rarity: "common" },
  { name: "Cosmic Puzzle Cube", rarity: "common" },
  { name: "Satellite Dish", rarity: "common" },
  { name: "Space Graffiti Spray", rarity: "common" },
  { name: "Solar Wind Chimes", rarity: "common" },
  { name: "Alien Hologram Card", rarity: "common" },
  { name: "Space Hammock", rarity: "common" },
  { name: "Celestial Whistle", rarity: "common" },
  { name: "Nebula Lighter", rarity: "common" },
  { name: "Space Harmonica", rarity: "common" },
  { name: "Lunar Rover Toy", rarity: "common" },
  { name: "Cosmic Paintbrush", rarity: "common" },
  { name: "Asteroid Marbles", rarity: "common" },
  { name: "Starship Blueprint (Miniature)", rarity: "common" },
  { name: "Pocket Nebula Viewer", rarity: "common" },
  { name: "Galactic Yoyo", rarity: "common" },
  { name: "Solar Flare Sunglasses", rarity: "common" },
  { name: "Meteor Shower Detector", rarity: "common" },
  { name: "Astro Lullaby Music Box", rarity: "common" },
  { name: "Advanced Spacesuit", rarity: "uncommon" },
  { name: "Plasma Cutter", rarity: "uncommon" },
  { name: "Alien Plant Specimen", rarity: "uncommon" },
  { name: "Gravity Manipulator Module", rarity: "uncommon" },
  { name: "Fuel Cell", rarity: "uncommon" },
  { name: "Ion Thruster Blueprint", rarity: "uncommon" },
  { name: "Quantum Communicator", rarity: "uncommon" },
  { name: "Solar Flare Detector", rarity: "uncommon" },
  { name: "Nebula Crystal Shard", rarity: "uncommon" },
  { name: "Stellar Navigation Computer", rarity: "uncommon" },
  { name: "Galactic Tricorder", rarity: "uncommon" },
  { name: "Wormhole Scanner", rarity: "uncommon" },
  { name: "Gravity Boots MKII", rarity: "uncommon" },
  { name: "Ionized Space Crystals", rarity: "uncommon" },
  { name: "Nebula Explorer's Journal", rarity: "uncommon" },
  { name: "Electromagnetic Compass", rarity: "uncommon" },
  { name: "Cosmic Relic Fragment", rarity: "uncommon" },
  { name: "Quantum Entanglement Device", rarity: "uncommon" },
  { name: "Hyperspace Navigational Chart", rarity: "uncommon" },
  { name: "Holographic Solar System Globe", rarity: "uncommon" },
  { name: "Space Colony Blueprint", rarity: "uncommon" },
  { name: "Rare Meteorite Sample", rarity: "uncommon" },
  { name: "Galactic Trading Card Set", rarity: "uncommon" },
  { name: "Enhanced Space Toolkit", rarity: "uncommon" },
  { name: "Alien Botany Encyclopedia", rarity: "uncommon" },
  { name: "Nebula-Inspired Artwork", rarity: "uncommon" },
  { name: "Microgravity Cookbook", rarity: "uncommon" },
  { name: "Quantum Mechanics Textbook", rarity: "uncommon" },
  { name: "Celestial Music Player", rarity: "uncommon" },
  { name: "Astral Projection Device", rarity: "uncommon" },
  { name: "Space Miner's Journal", rarity: "uncommon" },
  { name: "Cosmic Toolbox", rarity: "uncommon" },
  { name: "Nebula Gemstone", rarity: "uncommon" },
  { name: "Gravity-defying Paper Plane", rarity: "uncommon" },
  { name: "Space Weather Forecasting Device", rarity: "uncommon" },
  { name: "Alien Microorganisms Culture Kit", rarity: "uncommon" },
  { name: "Hyperspace Compass", rarity: "uncommon" },
  { name: "Antigravity Socks", rarity: "uncommon" },
  { name: "Quantum-Magnetic Chess Set", rarity: "uncommon" },
  { name: "Galactic Solar-Powered Lantern", rarity: "uncommon" },
  { name: "Nebula Puzzle", rarity: "uncommon" },
  { name: "Solar Flare Earrings", rarity: "uncommon" },
  { name: "Nebula Sand Timer", rarity: "uncommon" },
  { name: "Interstellar Radio Receiver", rarity: "uncommon" },
  { name: "Space Petroglyphs Tablet", rarity: "uncommon" },
  { name: "Zero-G Yoga Mat", rarity: "uncommon" },
  { name: "Nebula-Ink Pen Set", rarity: "uncommon" },
  { name: "Aurora Borealis Painting", rarity: "uncommon" },
  { name: "Moon Rover Model Kit", rarity: "uncommon" },
  { name: "Quantum Inversion Calculator", rarity: "uncommon" },
  { name: "Singularity-Powered Generator", rarity: "rare" },
  { name: "Nebula-Enhanced Hyperdrive", rarity: "rare" },
  { name: "Extragalactic Teleportation Device", rarity: "rare" },
  { name: "Quantum Warp Navigation Module", rarity: "rare" },
  { name: "Alien Starship Schematic Collection", rarity: "rare" },
  { name: "Hyper-Reality Visor", rarity: "rare" },
  { name: "Antigraviton Drive Prototype", rarity: "rare" },
  { name: "Nebula-Tinted Space Goggles", rarity: "rare" },
  { name: "Rare Galactic Fossil", rarity: "rare" },
  { name: "Ionized Nebula Sculpture", rarity: "rare" },
  { name: "Exoplanetary Habitat Blueprints", rarity: "rare" },
  { name: "Quantum Entropy Stabilizer", rarity: "rare" },
  { name: "Star Cluster Crystal Resonator", rarity: "rare" },
  { name: "Cosmic Clockwork Engine", rarity: "rare" },
  { name: "Exoplanetary Biodome", rarity: "rare" },
  { name: "Celestial Atlas of the Multiverse", rarity: "rare" },
  { name: "Quantum Phase Shield Generator", rarity: "rare" },
  { name: "Wormhole Gateway Key", rarity: "rare" },
  { name: "Nebula-Powered Starship Propulsion", rarity: "rare" },
  { name: "Rare Nebula-Woven Fabric", rarity: "rare" },
  { name: "Gravity-Warping Artifacts", rarity: "rare" },
  { name: "Star Core Alchemical Converter", rarity: "rare" },
  { name: "Quantum Thought Amplifier", rarity: "rare" },
  { name: "Celestial Empathy Crystal", rarity: "rare" },
  { name: "Alien Artifact Decryptor", rarity: "rare" },
  { name: "Interstellar Starport Plans", rarity: "rare" },
  { name: "Nebula-Forged Relic Sword", rarity: "rare" },
  { name: "Cosmic Quantum Harmonizer", rarity: "rare" },
  { name: "Quantum Matter Inversion Chamber", rarity: "rare" },
  { name: "Galactic Starship Nexus", rarity: "rare" },
  { name: "Nebula-Infused Crystalline Lens", rarity: "rare" },
  { name: "Celestial Resonance Harp", rarity: "rare" },
  { name: "Quantum Reality Manipulator", rarity: "rare" },
  { name: "Celestial Dust Collector", rarity: "rare" },
  { name: "Wormhole Stabilization Module", rarity: "rare" },
  { name: "Star Cluster Essence Elixir", rarity: "rare" },
  { name: "Exoplanetary Shielding Matrix", rarity: "rare" },
  { name: "Quantum Gravity Inverter", rarity: "rare" },
  { name: "Cosmic Chrono-Compass", rarity: "rare" },
  { name: "Nebula Nebulizer Synthesizer", rarity: "rare" },
  { name: "Singularity Lens Array", rarity: "rare" },
  { name: "Celestial Art Generator", rarity: "rare" },
  { name: "Galactic Hyperjump Beacon", rarity: "rare" },
  { name: "Quantum Molecular Assembler", rarity: "rare" },
  { name: "Starship Fleet Command Center", rarity: "rare" },
  { name: "Terraforming Module", rarity: "epic" },
  { name: "Starship AI Companion", rarity: "epic" },
  { name: "Singularity Core Reactor", rarity: "epic" },
  { name: "Ancient Star Map of Lost Worlds", rarity: "epic" },
  { name: "Interstellar Wormhole Key", rarity: "epic" },
  { name: "Quantum Phase Shield Generator", rarity: "epic" },
  { name: "Infinite Energy Crystal", rarity: "epic" },
  { name: "Precursor's Relic of Knowledge", rarity: "epic" },
  { name: "Nebula Explorer's Suit", rarity: "epic" },
  { name: "Celestial Guardian's Blade", rarity: "epic" },
  { name: "Eternal Time Manipulator", rarity: "epic" },
  { name: "Planet-Crafting Nanobots", rarity: "epic" },
  { name: "Infinite Warp Drive", rarity: "epic" },
  { name: "Cosmic Black Hole Generator", rarity: "epic" },
  { name: "The Ark of Cosmic Preservation", rarity: "epic" },
  { name: "Ancient Sentient Crystal", rarity: "epic" },
  { name: "Singularity-Linked Starship", rarity: "epic" },
  { name: "Cosmic Atlas of the Universe", rarity: "epic" },
  { name: "Cosmic Nexus Crystal", rarity: "epic" },
  { name: "Quantum Resonance Engine", rarity: "epic" },
  { name: "Celestial Star Forge", rarity: "epic" },
  { name: "Nebula Alchemist's Elixir", rarity: "epic" },
  { name: "Exoplanetary Genesis Seed", rarity: "epic" },
  { name: "Hyperstellar Wormhole Anchor", rarity: "epic" },
  { name: "Stellar Phoenix Feather", rarity: "epic" },
  { name: "The Chrono-Matrix Matrix", rarity: "epic" },
  { name: "Interdimensional Stargate", rarity: "epic" },
  { name: "Quantum Infinity Armor", rarity: "epic" },
  { name: "Nebula-Woven Starcloth", rarity: "epic" },
  { name: "Cosmic Graviton Manipulator", rarity: "epic" },
  { name: "Eternal Light Crystal", rarity: "epic" },
  { name: "Celestial Crystal of Enlightenment", rarity: "epic" },
  { name: "Quantum Anomaly Detector", rarity: "epic" },
  { name: "Celestial Harmonic Resonance Chamber", rarity: "epic" },
  { name: "Nebula Composer's Baton", rarity: "epic" },
  { name: "Cosmic Entropy Nullifier", rarity: "epic" },
  { name: "Hyperdimensional Star Chart", rarity: "epic" },
  { name: "Quantum Data Archive", rarity: "epic" },
  { name: "Celestial Ascension Wings", rarity: "epic" },
  { name: "Nebula-Wrought Starship Helm", rarity: "epic" },
  { name: "The Galactic Unity Medallion", rarity: "epic" },
  { name: "Cosmic Metamorphosis Machine", rarity: "epic" },
  { name: "Celestial Memory Crystal", rarity: "epic" },
  { name: "Quantum Entanglement Portal", rarity: "epic" },
  { name: "Exoplanetary Terraformer", rarity: "epic" },
  { name: "The Echoing Singularity", rarity: "epic" },
  { name: "Nebula-Infused Singing Crystal", rarity: "epic" },
  { name: "Cosmic Time Warper", rarity: "epic" },
  { name: "Quantum Rift Key", rarity: "epic" },
  { name: "Nebula Guardian's Shield", rarity: "epic" },
  { name: "Cosmic Singularity Manipulator", rarity: "legendary" },
  { name: "Celestial Starship Citadel", rarity: "legendary" },
  { name: "Eternal Nebula Prism", rarity: "legendary" },
  { name: "Quantum God Core", rarity: "legendary" },
  { name: "Stellar Ascension Cloak", rarity: "legendary" },
  { name: "Nebula Heart of Wisdom", rarity: "legendary" },
  { name: "Celestial Singularity Sword", rarity: "legendary" },
  { name: "Infinite Galaxy Key", rarity: "legendary" },
  { name: "Hyperdimensional Navigator", rarity: "legendary" },
  { name: "Cosmic Chrono Engine", rarity: "legendary" },
  { name: "The Cosmic Odyssey Library", rarity: "legendary" },
  { name: "Quantum Singularity Blade", rarity: "legendary" },
  { name: "Nebula of Eternal Knowledge", rarity: "legendary" },
  { name: "Celestial Time Bending Staff", rarity: "legendary" },
  { name: "The Celestial Matrix Gauntlet", rarity: "legendary" },
  { name: "Eternal Starship of the Ancients", rarity: "legendary" },
  { name: "Quantum World Builder", rarity: "legendary" },
  { name: "Nebula-Forged Celestial Armor", rarity: "legendary" },
  { name: "The Cosmic Enigma Amulet", rarity: "legendary" },
  { name: "The Universal Harmonic Conductor", rarity: "legendary" },
  { name: "Stellar Empowerment Gem", rarity: "legendary" },
  { name: "Quantum Reality Sculptor", rarity: "legendary" },
  { name: "The Celestial Architect's Blueprint", rarity: "legendary" },
  { name: "Cosmic Essence of Creation", rarity: "legendary" },
  { name: "Eternal Harmonic Resonance Engine", rarity: "legendary" },
  { name: "The Singularity Voice", rarity: "legendary" },
  { name: "The Quantum Nexus Crown", rarity: "legendary" },
  { name: "Nebula-Infused Ethereal Wings", rarity: "legendary" },
  { name: "The Cosmic Symphonic Baton", rarity: "legendary" },
  { name: "Celestial Memory Sphere", rarity: "legendary" },
  { name: "The Infinite Galaxy Navigator", rarity: "legendary" },
  { name: "Quantum Portal of Possibility", rarity: "legendary" },
  { name: "The Celestial Key to All Realms", rarity: "legendary" },
  { name: "Nebula Whisperer's Staff", rarity: "legendary" },
  { name: "The Celestial Forge Anvil", rarity: "legendary" },
  { name: "The Quantum Heart of Infinity", rarity: "legendary" },
  { name: "Cosmic Symphony Conductor", rarity: "legendary" },
  { name: "Nebula Dreamweaver's Loom", rarity: "legendary" },
  { name: "Eternal Starship Armada", rarity: "legendary" },
  { name: "The Omni-Reality Lens", rarity: "legendary" },
  { name: "Celestial Soul Infinity Orb", rarity: "legendary" },
  { name: "The Singularity's Echoing Cry", rarity: "legendary" },
  { name: "The Nebula's Eternal Watch", rarity: "legendary" },
  { name: "Quantum Star Forging Anvil", rarity: "legendary" },
  { name: "The Celestial's All-Knowing Eye", rarity: "legendary" },
  { name: "Cosmic Thought Controller", rarity: "legendary" },
  { name: "The Quantum Oracle's Crown", rarity: "legendary" },
  { name: "The Celestial Scribe's Quill", rarity: "legendary" },
  { name: "Eternal Nebula of Creation", rarity: "legendary" },
  { name: "The Cosmic Voyager's Journal", rarity: "legendary" },
  // Add more items here.
];

// Function to randomly select an item from the array based on rarity.
export function getRandomItem(): Item {
    const rarityWeights = {
      common: 60,
      uncommon: 20,
      rare: 10,
      epic: 5,
      legendary: 1,
    };
  
    // Generate a random number between 0 and the total weight.
    const totalWeight = Object.values(rarityWeights).reduce((acc, weight) => acc + weight, 0);
    const randomValue = Math.floor(Math.random() * totalWeight);
  
    // Determine the rarity based on the random number and rarity weights.
    let selectedRarity: keyof typeof rarityWeights = "common";
    let cumulativeWeight = 0;
    for (const rarity in rarityWeights) {
      cumulativeWeight += rarityWeights[rarity as keyof typeof rarityWeights];
      if (randomValue < cumulativeWeight) {
        selectedRarity = rarity as keyof typeof rarityWeights;
        break;
      }
    }
  
    // Filter items of the selected rarity.
    const itemsOfSelectedRarity = items
      .filter((item) => item.rarity === selectedRarity)
      .filter((item): item is Item => item !== undefined); // Filter out undefined values.
  
    // Randomly select an item of the selected rarity.
    const randomIndex = Math.floor(Math.random() * itemsOfSelectedRarity.length);
  
    return itemsOfSelectedRarity[randomIndex]!;
  }
  
  
  // Example usage:
  const openedItem = getRandomItem();
  console.log(`You received: ${openedItem.name} (${openedItem.rarity} rarity)`);
  
